CREATE TABLE IF NOT EXISTS refresh_token
(
    id       BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    token  VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expired_date TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS password VARCHAR(255) NOT NULL DEFAULT '';
