CREATE TABLE IF NOT EXISTS refresh_token
(
    id       BIGINT AUTO_INCREMENT PRIMARY KEY,
    token  VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    expired_date TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
